window.DANCE_YOUTUBE_LIBRARY = {
  Pop: [
    { id: "xFrGuyw1V8s", title: "ABBA - Dancing Queen (Official Music Video)", source: "YouTube" },
    { id: "eNvUS-6PTbs", title: "Modern Talking - Cheri Cheri Lady (Official Video)", source: "YouTube" },
    { id: "XEjLoHdbVeE", title: "ABBA - Gimme! Gimme! Gimme! (A Man After Midnight)", source: "YouTube" },
    { id: "16y1AkoZkmQ", title: "Boney M. - Rasputin (Sopot Festival 1979)", source: "YouTube" },
    { id: "W_dDNNEdIJg", title: "Stayin' Alive (From 'Saturday Night Fever' Soundtrack)", source: "YouTube" },
    { id: "LUGga_VPeTo", title: "Best Songs of 70's Disco Music | Greatest Hits of Seventies Disco Fashion", source: "YouTube" },
    { id: "pYeNaad2NKI", title: "Studio 54 Super Disco Mix (The Best of 70s Disco Classic Series)", source: "YouTube" },
    { id: "qizKODkJVdY", title: "70's Best Disco, Funk & R'n'B Hits Vol.1 (Serega Bolonkin Video Mix)", source: "YouTube" },
    { id: "8H_369EIdo0", title: "I Feel Love", source: "YouTube" },
    { id: "R2lWpSjKCco", title: "Born To Be Alive Patrick Hernandez", source: "YouTube" },
  ],
  EDM: [
    { id: "gfOIkudBWc8", title: "Music Mix 2026 | Music That Make You Feel BADASS | EDM Remixes of Popular Songs | Bass Boosted 2026", source: "YouTube" },
    { id: "sVksqf0_iZM", title: "Music Mix 2026 | Party Club Dance 2026 | Best Remixes Of Popular Songs 2026 MEGAMIX", source: "YouTube" },
    { id: "IFN7kDtdu4w", title: "Top EDM Music Mix 2025 | EDM Remixes of Popular Songs | EDM Gaming Music Mix", source: "YouTube" },
    { id: "FkuFN41YUts", title: "Music Mix 2026 | Music That Make You Feel BADASS | EDM Remixes of Popular Songs | Bass Boosted 2026", source: "YouTube" },
    { id: "MurAakwfxEY", title: "Music Mix 2026 | EDM Remixes of Popular Songs | EDM Mood Up", source: "YouTube" },
    { id: "NF5SX65znjU", title: "Bass Boosted EDM Music Mix 2026 | Popular Song Remixes | Top EDM Tracks of 2026", source: "YouTube" },
    { id: "gaEsFOm453g", title: "Music That Make You Feel BADASS | EDM Remixes of Popular Songs | EDM Music Mix | Bass Boosted", source: "YouTube" },
    { id: "aaWs5SBbAts", title: "EDM Bass Boosted Music Mix 2026 | EDM Remixes of Popular Songs | EDM Music Mix 2026", source: "YouTube" },
    { id: "n6gmec4NJWc", title: "Top EDM Music Mix 2025 | EDM Remixes of Popular Songs | EDM Gaming Music Mix", source: "YouTube" },
    { id: "sC8BK4uGnEU", title: "Party Mashup Mix 2026 | The Best EDM Remixes & Mashups Of Popular Songs", source: "YouTube" },
  ],
  Waltz: [
    { id: "cN1vniebhzM", title: "Waltz No.2 - Dmitri Shostakovich | Andre Rieu | Second Waltz | Wedding Dance Choreography", source: "YouTube" },
    { id: "mmCnQDUSO4I", title: "Dmitri Shostakovich - Waltz No. 2", source: "YouTube" },
    { id: "WcQ--VNWFHY", title: "WALTZ music | Come Thou Every Blessing", source: "YouTube" },
    { id: "5yCKtMym0xA", title: "WALTZ music | Valerie", source: "YouTube" },
    { id: "7j4Ek5OWnxo", title: "[1 HOUR] NON-STOP WALTZ MUSIC MIX | Dancesport & Ballroom Dance Music", source: "YouTube" },
    { id: "UBf0xGUeocU", title: "Slow Waltz music: Valerie | Dancesport & Ballroom Dance Music", source: "YouTube" },
    { id: "oFmkKehJACA", title: "Slow Waltz | Ballroom Dance & DanceSport Music #5", source: "YouTube" },
    { id: "uV4BjBCyEYs", title: "SLOW WALTZ | Dj Ice - River Flows In You (Classic Ver. / Full Length)", source: "YouTube" },
    { id: "r8MYgQz3CCc", title: "SLOW WALTZ | Dj Ice ft. Clair - Never Enough (from The Greatest Showman)", source: "YouTube" },
    { id: "_PEDkdHN_0U", title: "NON-STOP Waltz Music Mix | Ballroom Dance Music", source: "YouTube" },
    { id: "bBzlV2E3KrE", title: "Menuet", source: "YouTube" },
  ],
};
